trigger:
  branches:
    include: 
    - main
  paths:
    include:
    - src/PipelineExample.App3*

pr: none # will disable PR builds (but not CI builds)

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:  
  - job: BuildGateway
    displayName: 'Build Gateway'
    steps:
    - task: DotNetCoreCLI@2
      displayName: 'Restore'
      inputs:
        command: 'restore'
        projects: 'src/PipelineExample.App3'
        feedsToUse: 'select'
        vstsFeed: '1a343071-4c92-42ed-8b42-1526a6b90483'

    - task: DotNetCoreCLI@2
      displayName: 'Run Tests'
      inputs:
        command: 'test'
        projects: 'src/PipelineExample.App3.Tests/*.Tests.csproj'
        testRunTitle: 'Gateway Test Run'

- stage: DevDeploy
  jobs:
    - job: DevDeployGateway
      displayName: "Dev Deploy Gateway"
      steps:
      - script: echo Deploy Gateway to Dev
        displayName: 'Dev Deploy Gateway'
