trigger:
  branches:
    include: 
    - main
  paths:
    include:
    - src/PipelineExample.App1*
    - src/PipelineExample.App2*

pr: none # will disable PR builds (but not CI builds)

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:  
  - job: BuildApi1
    displayName: 'Build Api 1'
    steps:
    - task: DotNetCoreCLI@2
      displayName: 'Restore'
      inputs:
        command: 'restore'
        projects: 'src/PipelineExample.App1'
        feedsToUse: 'select'
        vstsFeed: '1a343071-4c92-42ed-8b42-1526a6b90483'

    - task: DotNetCoreCLI@2
      displayName: 'Run Tests'
      inputs:
        command: 'test'
        projects: 'src/PipelineExample.App1.Tests/*.Tests.csproj'
        testRunTitle: 'Api 1 Test Run'

  - job: BuildApp2
    displayName: 'Build Api 2'
    steps:
    - task: DotNetCoreCLI@2
      displayName: 'Restore'
      inputs:
        command: 'restore'
        projects: 'src/PipelineExample.App2'
        feedsToUse: 'select'
        vstsFeed: '1a343071-4c92-42ed-8b42-1526a6b90483'

    - task: DotNetCoreCLI@2
      displayName: 'Run Tests'
      inputs:
        command: 'test'
        projects: 'src/PipelineExample.App2.Tests/*.Tests.csproj'
        testRunTitle: 'Api 2 Test Run'

 

- stage: DevDeploy
  jobs:
    - job: DevDeployApi1
      displayName: 'Dev Deploy Api 1'
      steps:
      - script: echo Deploy Api 1 to Dev
        displayName: 'Dev Deploy Api 1'

    - job: DevDeployApi2
      displayName: 'Dev Deploy Api 2'
      steps:
      - script: echo Deploy Api 2 to Dev
        displayName: 'Dev Deploy Api 2'