trigger:
  branches:
    include: 
    - main
  paths:
    include:
    - src/PipelineExample.App1*
    - src/PipelineExample.App2*

pr: none # will disable PR builds (but not CI builds)

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:  
  - job: BuildApp1
    steps:
    - task: DotNetCoreCLI@2
      displayName: 'Restore App1'
      inputs:
        command: 'restore'
        projects: 'src/PipelineExample.App1'
        feedsToUse: 'select'
        vstsFeed: '1a343071-4c92-42ed-8b42-1526a6b90483'

    - task: DotNetCoreCLI@2
      displayName: 'Run App1 Tests'
      inputs:
        command: 'test'
        projects: 'src/PipelineExample.App1.Tests/*.Tests.csproj'
        testRunTitle: 'App1 Test Run'

  - job: BuildApp2
    steps:
    - task: DotNetCoreCLI@2
      displayName: 'Restore App2'
      inputs:
        command: 'restore'
        projects: 'src/PipelineExample.App2'
        feedsToUse: 'select'
        vstsFeed: '1a343071-4c92-42ed-8b42-1526a6b90483'

    - task: DotNetCoreCLI@2
      displayName: 'Run App2 Tests'
      inputs:
        command: 'test'
        projects: 'src/PipelineExample.App2.Tests/*.Tests.csproj'
        testRunTitle: 'App2 Test Run'

 

- stage: ReleaseDev
  jobs:
    - job: ReleaseApp1Dev
      steps:
      - script: echo Deploy App 1 to Dev
        displayName: 'Dev Deploy App1'

    - job: ReleaseApp2Dev
      steps:
      - script: echo Deploy App 2 to Dev
        displayName: 'Dev Deploy App2'