trigger:
    branches:
        include:
        - main

variables:
  isMainBranch: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]

pool:
  vmImage: "ubuntu-latest"

stages:
- stage: Build
  variables:
    GIT_BRANCH: $(Build.SourceBranch)
    GIT_COMMIT: $(Build.SourceVersion)
    solutionDirectory: "src"
    solutionFile: "$(solutionDirectory)/DealStacker.Api.sln"
    appDirectory: "$(solutionDirectory)/DealStacker.Api.Application"
    identityServerDirectory: "$(solutionDirectory)/Dealstacker.IdentityServer"
    pcpSyncherDirectory: "$(solutionDirectory)/DealStacker.PcpCacheSyncher"
    branchContactImportDirectory: "$(solutionDirectory)/DealStacker.BranchContactImport"
  jobs:
  - template: pipeline/build/build.yml
    displayName: 'Build App 1'
    parameters:
      solutionFile: "$(solutionDirectory)/DealStacker.Api1.sln"

  - template: pipeline/build/build.yml
    displayName: 'Build App 2'
    parameters:
      solutionFile: "$(solutionDirectory)/DealStacker.Api2.sln"

  - template: pipeline/build/build.yml
    displayName: 'Build App 3'
    parameters:
      solutionFile: "$(solutionDirectory)/DealStacker.Api3.sln"